### ISSUE TITLE
substring remaining after rmdup

### ISSUE THREAD

**Issue by bvalot** [jts/sga#162]
Hi,

I'm actually discover sga software and I try to assembly bacterial genome with 2x150bp illumina library.
I run the following command : 
`sga preprocess -p 1 -q 20 -m 50  DHS01_R1_100x.fastq.gz DHS01_R2_100x.fastq.gz > DHS01_trim_100x_preprocess.fastq`
`sga index -t 12 DHS01_trim_100x_preprocess.fastq`
`sga correct -t 12 -m 60 DHS01_trim_100x_preprocess.fastq`
`sga rmdup -t 12 DHS01_trim_100x_preprocess.fastq`
`sga overlap -t 12 -m 60 DHS01_trim_100x_preprocess.fastq`

And get the following error, although I performed the rmdup step. I have miss something? 
`[sga::overlap] starting parallel-mode overlap computation with 12 threads`
`Error: substring read found during overlap computation.`
`Please run sga rmdup before sga overlap`

I make a mistake?

**Comment by jts** [comment]
Hi @bvalot,

The problem here is that you did not re-index your reads after error correction. See here for the suggested bacterial workflow: https://github.com/jts/sga/blob/master/src/examples/sga-ecoli-miseq.sh

Please note SGA is deprecated and you should use a different assembler like SPAdes instead.

Jared

**Comment by bvalot** [comment]
Thanks for your response.

Why it is deprecated?  I actually used Spades, but want to evaluated other possible tools in comparison.

**Comment by jts** [comment]
Other tools outperform it and I don't have enough time to maintain it anymore
